server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false


logging:
    level:
        com.netflix.eureka: DEBUG
        com.netflix.discovery: DEBUG