server:
  port: 9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
  application:
    name: Spring-Eureka-Client
