server:
  port: 9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: Spring-Eureka-Client

logging:
  level:
    org.springframework.cloud.config: DEBUG